import { useCallback, useEffect, useRef, useState } from 'react';
import { Link } from 'react-router-dom';
import { Camera, Globe2, Navigation, ShieldAlert, ArrowRight, LoaderCircle } from 'lucide-react';
import { api } from '../lib/api';
import { analysisFailureMessage } from '../lib/analysis';
import { toLocalDateTimeInput } from '../lib/time';
import { GoogleRouteMap } from '../components/GoogleRouteMap';
import { IncidentBadge } from '../components/IncidentBadge';
import { useAuth } from '../context/AuthContext';
import type { Coordinate, RealAnalysisResult, RealIncident, RealIncidentDetail, RealPlan } from '../types/navigation';
const field = 'w-full bg-slate-950 border border-slate-700 rounded-xl p-3 text-sm text-white';
const distance = (meters: number) => meters < 1000 ? `${meters} m` : `${(meters / 1000).toFixed(2)} km`;

export function RealNavigationPage() {
  const { isAuthenticated, isModerator } = useAuth();
  const [configured, setConfigured] = useState<boolean | null>(null);
  const [origin, setOrigin] = useState(''), [destination, setDestination] = useState('');
  const [plan, setPlan] = useState<RealPlan | null>(null), [incidents, setIncidents] = useState<RealIncident[]>([]);
  const [loading, setLoading] = useState(false), [error, setError] = useState('');
  const requestVersion = useRef(0);
  const [pin, setPin] = useState<Coordinate | null>(null), [latitude, setLatitude] = useState(''), [longitude, setLongitude] = useState('');
  const [label, setLabel] = useState(''), [claim, setClaim] = useState('BLOCKED'), [description, setDescription] = useState('');
  const [observedAt, setObservedAt] = useState(toLocalDateTimeInput(new Date()));
  const [photo, setPhoto] = useState<File | null>(null), [preview, setPreview] = useState('');
  const [submitting, setSubmitting] = useState(false), [reportError, setReportError] = useState('');
  const [result, setResult] = useState<RealAnalysisResult | null>(null), [selected, setSelected] = useState<RealIncidentDetail | null>(null);
  const [evidenceId, setEvidenceId] = useState(''), [reason, setReason] = useState(''), [attestation, setAttestation] = useState(false);
  const refreshIncidents = useCallback(async () => { const response = await api.getRealIncidents(); setIncidents(response.incidents); }, []);
  useEffect(() => {
    let active = true;
    api.navigationStatus().then(s => { if (active) setConfigured(s.configured); }).catch(e => { if (active) setError(e.message); });
    api.getRealIncidents().then(r => { if (active) setIncidents(r.incidents); }).catch(e => { if (active) setError(e.message); });
    return () => { active = false; requestVersion.current++; };
  }, []);
  useEffect(() => { if (!photo) { setPreview(''); return; } const url = URL.createObjectURL(photo); setPreview(url); return () => URL.revokeObjectURL(url); }, [photo]);
  const selectPin = useCallback((p: Coordinate) => { setPin(p); setLatitude(p.lat.toFixed(6)); setLongitude(p.lng.toFixed(6)); }, []);
  function changeJourney(setter: (v: string) => void, value: string) { requestVersion.current++; setLoading(false); setPlan(null); setter(value); }
  async function calculate(event: React.FormEvent) {
    event.preventDefault(); const version = ++requestVersion.current; setLoading(true); setError(''); setPlan(null);
    try { const response = await api.planRealRoute(origin.trim(), destination.trim()); if (version === requestVersion.current) setPlan(response); }
    catch (e) { if (version === requestVersion.current) setError((e as Error).message); }
    finally { if (version === requestVersion.current) setLoading(false); }
  }
  async function inspect(incident: RealIncident) {
    setReportError('');
    try { const response = await api.getRealIncident(incident.id); setSelected(response.incident); selectPin(incident); setLabel(incident.label); setEvidenceId(''); }
    catch (e) { setReportError((e as Error).message); }
  }
  async function submitReport(event: React.FormEvent) {
    event.preventDefault(); setReportError(''); setResult(null);
    const lat = Number(latitude), lng = Number(longitude);
    if (!latitude.trim() || !longitude.trim() || !Number.isFinite(lat) || !Number.isFinite(lng) || Math.abs(lat) > 90 || Math.abs(lng) > 180) { setReportError('Choose the obstruction location on the map or enter valid coordinates.'); return; }
    if (!photo || !['image/jpeg', 'image/png'].includes(photo.type) || photo.size > 5 * 1024 * 1024) { setReportError('Choose a JPEG or PNG photograph up to 5 MB.'); return; }
    if (!Number.isFinite(new Date(observedAt).getTime())) { setReportError('Enter a valid observation time.'); return; }
    const body = new FormData(); body.set('photo', photo); body.set('latitude', latitude); body.set('longitude', longitude); body.set('label', label);
    body.set('claim', claim); body.set('description', description); body.set('observedAt', new Date(observedAt).toISOString()); if (selected) body.set('incidentId', selected.id);
    setSubmitting(true);
    try { const response = await api.submitRealReport(body); setResult(response); setPlan(null); requestVersion.current++; await refreshIncidents(); setSelected((await api.getRealIncident(response.incidentId)).incident); }
    catch (e) { setReportError((e as Error).message); }
    finally { setSubmitting(false); }
  }
  async function retry(reportId: string) {
    setSubmitting(true); setReportError('');
    try { const response = await api.retryRealAnalysis(reportId); setResult(response); setPlan(null); requestVersion.current++; await refreshIncidents(); setSelected((await api.getRealIncident(response.incidentId)).incident); }
    catch (e) { setReportError((e as Error).message); } finally { setSubmitting(false); }
  }
  async function moderate(action: 'CONFIRM_BLOCKED' | 'CLEAR' | 'DISMISS') {
    if (!selected) return; setReportError(''); setSubmitting(true);
    try {
      await api.verifyRealIncident(selected.id, { action, expectedVersion: selected.version, evidenceReportId: evidenceId || undefined, reason,
        blockedProfiles: action === 'CONFIRM_BLOCKED' ? ['GENERAL_WALK'] : undefined, attestation: action === 'CLEAR' ? attestation : undefined });
      setSelected((await api.getRealIncident(selected.id)).incident); setPlan(null); requestVersion.current++; await refreshIncidents();
    } catch (e) { setReportError((e as Error).message); } finally { setSubmitting(false); }
  }
  return <div className="space-y-6">
    <div className="flex flex-wrap items-start justify-between gap-4"><div><p className="eyebrow flex gap-2 items-center"><Globe2 className="w-4 h-4" aria-hidden="true" />Optional real navigation</p><h1 className="text-3xl sm:text-4xl font-bold mt-3">Real route. <span className="text-emerald-300">Community warnings.</span></h1><p className="text-slate-400 mt-3 max-w-3xl">Google provides the walking route. RouteShield checks real-location reports before you travel and selects an unaffected returned alternative when available.</p></div><Link to="/plan" className="secondary-button">Maple Ward demo <ArrowRight className="w-4 h-4" aria-hidden="true" /></Link></div>
    <section className="surface p-4 text-sm text-amber-100 border-amber-400/20"><strong>Walking access is unverified.</strong> Real routes are not certified step-free or wheelchair-safe. Google walking routes may omit sidewalks or pedestrian paths. Use caution and check local conditions.</section>
    {configured === false && <p role="status" className="surface p-5 text-amber-200">Google routing setup is pending. <Link to="/plan" className="underline">Open the working Maple Ward demo.</Link></p>}
    {!isAuthenticated && <p className="surface p-4 text-sm text-slate-300">Sign in to request Google routes or upload real-location evidence. <Link to="/login?redirect=%2Fnavigate" className="text-emerald-300 underline">Log in</Link></p>}
    <form onSubmit={calculate} className="surface p-5 grid sm:grid-cols-[1fr_1fr_auto] items-end gap-4"><div><label htmlFor="real-origin" className="block text-sm mb-2">Real origin</label><input id="real-origin" required minLength={3} maxLength={250} value={origin} onChange={e => changeJourney(setOrigin, e.target.value)} placeholder="e.g. RK Beach, Visakhapatnam" className={field} /></div><div><label htmlFor="real-destination" className="block text-sm mb-2">Real destination</label><input id="real-destination" required minLength={3} maxLength={250} value={destination} onChange={e => changeJourney(setDestination, e.target.value)} placeholder="e.g. Submarine Museum, Visakhapatnam" className={field} /></div><button disabled={!isAuthenticated || configured !== true || loading} className="primary-button disabled:opacity-50"><Navigation className="w-4 h-4" aria-hidden="true" />{loading ? 'Checking route…' : 'Check before travel'}</button></form>
    {loading && <p role="status" className="text-emerald-200">Requesting real Google walking routes and checking active geolocated incidents…</p>}
    {error && <p role="alert" className="surface p-4 text-red-200 border-red-400/30">{error}</p>}
    {plan && <section className={`surface p-6 space-y-4 ${plan.baseline?.nearbyIncidents.length ? 'border-amber-400/40' : ''}`} aria-live="polite"><p className="eyebrow">Before you start traveling</p><h2 className="text-xl font-semibold">{plan.baseline?.avoided ? 'Obstruction reported near your original route' : plan.baseline?.nearbyIncidents.length ? 'Unverified reports near this route' : plan.status === 'NO_PROVIDER_ROUTE' ? 'No walking route returned' : 'No known reports near this route'}</h2><p className="text-slate-300">{plan.explanation}</p><div className="grid sm:grid-cols-2 gap-4">{plan.baseline && <div className="bg-slate-950 rounded-xl p-4"><span className="text-slate-400 text-sm">Original Google route</span><p className="text-2xl font-bold mt-2">{distance(plan.baseline.distanceMeters)}</p></div>}<div className="bg-slate-950 rounded-xl p-4"><span className="text-slate-400 text-sm">{plan.status === 'ALTERNATIVE' ? 'Recommended alternative' : 'Current recommendation'}</span><p className="text-2xl font-bold mt-2 text-emerald-300">{plan.recommended ? distance(plan.recommended.distanceMeters) : 'No verified alternative'}</p>{plan.recommended && <p className="text-sm mt-1 text-slate-400">Google estimate: {Math.ceil(plan.recommended.durationSeconds / 60)} min walking</p>}</div></div>{plan.baseline?.nearbyIncidents.map(i => <div key={i.id} className="flex flex-wrap gap-3 items-center"><ShieldAlert className="w-4 h-4 text-amber-300" aria-hidden="true" /><span>{i.label}</span><IncidentBadge status={i.status} /><button className="text-emerald-300 underline text-sm" onClick={() => inspect(i)}>Inspect report</button></div>)}<p className="text-xs text-slate-400">{plan.matching} Checked {new Date(plan.checkedAt).toLocaleTimeString()}.</p>{[...new Set([...(plan.baseline?.warnings ?? []), ...(plan.recommended?.warnings ?? [])])].map(w => <p key={w} className="text-sm text-amber-200">Google warning: {w}</p>)}</section>}
    {import.meta.env.VITE_GOOGLE_MAPS_BROWSER_API_KEY ? <GoogleRouteMap plan={plan} incidents={incidents} pin={pin} onPin={selectPin} /> : <p className="surface p-5 text-slate-300">The real map is waiting for its restricted browser key. Maple Ward continues to work.</p>}
    {plan?.recommended && <section className="surface p-5"><h2 className="font-semibold mb-3">Text itinerary from Google</h2>{plan.recommended.instructions.length ? <ol className="space-y-3 list-decimal ml-5 text-sm text-slate-300">{plan.recommended.instructions.map((step, i) => <li key={i}>{step}</li>)}</ol> : <p className="text-slate-400">Google did not provide text instructions for this route.</p>}</section>}
    <div className="grid lg:grid-cols-[1fr_1fr] gap-6"><section className="surface p-5 space-y-4"><h2 className="text-xl font-semibold flex items-center gap-2"><Camera className="w-5 h-5 text-emerald-300" aria-hidden="true" />Report a real obstruction</h2><p className="text-sm text-slate-400">Select the actual path location. Pin location and capture time are your claims; Gemini assesses only the photo. Reports are community-visible. Avoid faces or private information. Do not submit historical demo photos as current real incidents.</p>
    {selected && <div className="text-sm text-amber-200">Adding evidence to: {selected.label} <button onClick={() => { setSelected(null); setResult(null); }} className="underline ml-3">Start a separate report</button></div>}
    <form onSubmit={submitReport} className="space-y-4"><div><label htmlFor="real-label" className="block text-sm mb-2">Affected path / landmark</label><input id="real-label" className={field} value={label} onChange={e => setLabel(e.target.value)} required maxLength={120} /></div><div className="grid grid-cols-2 gap-3"><div><label htmlFor="real-latitude" className="block text-sm mb-2">Latitude</label><input id="real-latitude" className={field} type="number" step="any" min="-90" max="90" required value={latitude} disabled={Boolean(selected)} onChange={e => setLatitude(e.target.value)} /></div><div><label htmlFor="real-longitude" className="block text-sm mb-2">Longitude</label><input id="real-longitude" className={field} type="number" step="any" min="-180" max="180" required value={longitude} disabled={Boolean(selected)} onChange={e => setLongitude(e.target.value)} /></div></div><div><label htmlFor="real-photo" className="block text-sm mb-2">Obstruction photo · JPEG / PNG · 5 MB max</label><input id="real-photo" type="file" accept="image/jpeg,image/png" required onChange={e => setPhoto(e.target.files?.[0] ?? null)} className="block w-full text-sm" />{preview && <img src={preview} alt="Selected obstruction evidence preview" className="rounded-xl mt-3 max-h-52 w-full object-contain bg-slate-950" />}</div><div className="grid sm:grid-cols-2 gap-3"><div><label htmlFor="real-claim" className="block text-sm mb-2">Your observation</label><select id="real-claim" value={claim} onChange={e => setClaim(e.target.value)} className={field}><option value="BLOCKED">Blocked</option><option value="UNCERTAIN">Uncertain</option><option value="CLEAR">Clearance evidence</option></select></div><div><label htmlFor="real-observed" className="block text-sm mb-2">Observed at</label><input id="real-observed" type="datetime-local" required value={observedAt} onChange={e => setObservedAt(e.target.value)} className={field} /></div></div><div><label htmlFor="real-description" className="block text-sm mb-2">Description (optional)</label><textarea id="real-description" value={description} onChange={e => setDescription(e.target.value)} maxLength={500} className={field} /></div><button disabled={!isAuthenticated || submitting} className="primary-button w-full disabled:opacity-50">{submitting ? <LoaderCircle className="w-4 h-4 animate-spin" aria-hidden="true" /> : <Camera className="w-4 h-4" aria-hidden="true" />}{submitting ? 'Saving photo and running Gemini…' : 'Report obstruction & analyze photo'}</button></form>
    {reportError && <p role="alert" className="text-red-200">{reportError}</p>}{result && <div role="status" className="bg-slate-950 rounded-xl p-4 space-y-3"><h3 className="font-semibold">{result.analysisStatus === 'COMPLETE' ? 'Real Gemini analysis complete' : 'Report saved; analysis failed'}</h3><p className="text-xs text-slate-400">Model: {result.model ?? 'Unavailable'} · Incident: {result.incidentStatus}</p>{result.analysis ? <><p>{result.analysis.obstruction_type.replace(/_/g, ' ')} · {result.analysis.severity}</p><ul className="text-sm text-slate-300 list-disc ml-5">{result.analysis.observations.map(o => <li key={o}>{o}</li>)}</ul><p className="text-sm">Apparent walking passage: {result.analysis.passability.general_walk}</p></> : <p className="text-amber-200 text-sm">{analysisFailureMessage(result.errorCode)}</p>}<p className="text-xs text-slate-400">AI does not authorize reopening. Fresh independent evidence or moderator verification controls incident status.</p></div>}</section>
    <section className="surface p-5 space-y-4"><h2 className="text-xl font-semibold">Real-location community incidents</h2><p className="text-sm text-slate-400">Only real-location reports appear here. No Maple Ward incidents are placed on this map.</p>{!incidents.length && <p className="text-slate-300 text-sm">No real incidents reported yet. Community coverage is incomplete.</p>}{incidents.map(i => <button key={i.id} onClick={() => inspect(i)} disabled={!isAuthenticated} className="w-full text-left bg-slate-950 border border-slate-800 rounded-xl p-4 disabled:opacity-60"><span className="font-medium block mb-2">{i.label}</span><IncidentBadge status={i.status} /><span className="block mt-2 text-xs text-slate-400">{i.lat.toFixed(6)}, {i.lng.toFixed(6)} · {new Date(i.lastEvidenceAt).toLocaleString()}</span></button>)}
    {selected && <div className="border-t border-slate-800 pt-4 space-y-4"><h3 className="font-semibold">Evidence: {selected.label}</h3>{selected.reports.map(r => <div key={r.id} className="bg-slate-950 rounded-xl p-4 space-y-2">{r.signedPhotoUrl && <img src={r.signedPhotoUrl} alt={`Evidence for ${selected.label}`} className="max-h-44 rounded-lg object-contain" />}<p className="text-sm">{r.reporterName} · {r.claim} · {r.analysisStatus}</p><p className="text-xs text-slate-400">{r.analysisModel} · {new Date(r.observedAt).toLocaleString()}</p>{r.analysisJson?.observations.map(o => <p key={o} className="text-sm text-slate-300">{o}</p>)}{r.analysisStatus === 'FAILED' && r.analysisAttempts < 3 && <button disabled={submitting} onClick={() => retry(r.id)} className="secondary-button">Retry Gemini analysis</button>}</div>)}
    {isModerator && selected.status !== 'CLEARED' && !selected.dismissedAt && <div className="space-y-3"><h3 className="font-semibold text-purple-200">Moderator verification</h3><label htmlFor="real-verification-evidence" className="block text-sm">Supporting analyzed evidence</label><select id="real-verification-evidence" className={field} value={evidenceId} onChange={e => setEvidenceId(e.target.value)}><option value="">Select evidence</option>{selected.reports.filter(r => r.analysisStatus === 'COMPLETE').map(r => <option key={r.id} value={r.id}>{r.reporterName} · {r.claim}</option>)}</select><label htmlFor="real-verification-reason" className="block text-sm">Verification reason</label><textarea id="real-verification-reason" value={reason} onChange={e => setReason(e.target.value)} maxLength={1000} className={field} /><label className="flex gap-2 text-sm"><input type="checkbox" checked={attestation} onChange={e => setAttestation(e.target.checked)} />I checked the entire affected path before reopening.</label><div className="flex flex-wrap gap-2"><button disabled={submitting || !reason.trim()} onClick={() => moderate('CONFIRM_BLOCKED')} className="secondary-button">Confirm walking block</button><button disabled={submitting || !reason.trim()} onClick={() => moderate('CLEAR')} className="secondary-button">Verify reopening</button>{selected.status === 'UNVERIFIED' && <button disabled={submitting || !reason.trim()} onClick={() => moderate('DISMISS')} className="secondary-button">Dismiss</button>}</div></div>}</div>}</section></div>
  </div>;
}
